version: '3.8'

# This file automatically extends docker-compose.yml for local development
services:
  api:
    environment:
      - DEBUG=true
    volumes:
      - .:/app
    
  frontend:
    volumes:
      - ./frontend:/app/frontend