# monitoring/grafana/datasources/prometheus.yml - Grafana data source
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true