# .github/workflows/cleanup.yml - Cleanup old resources
name: Cleanup

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  cleanup-ecr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Cleanup old ECR images
      run: |
        # Keep only the latest 10 images
        aws ecr describe-images \
          --repository-name multimodal-ai-api \
          --query 'sort_by(imageDetails,& imagePushedAt)[:-10]' \
          --output json | \
        jq '.[] | .imageDigest' -r | \
        while read digest; do
          aws ecr batch-delete-image \
            --repository-name multimodal-ai-api \
            --image-ids imageDigest=$digest
        done
        
        aws ecr describe-images \
          --repository-name multimodal-ai-frontend \
          --query 'sort_by(imageDetails,& imagePushedAt)[:-10]' \
          --output json | \
        jq '.[] | .imageDigest' -r | \
        while read digest; do
          aws ecr batch-delete-image \
            --repository-name multimodal-ai-frontend \
            --image-ids imageDigest=$digest
        done
